spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/MyProject
          jwk-set-uri: http://localhost:8080/realms/MyProject/protocol/openid-connect/certs

  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service
  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "http://localhost:4200"
        allowedMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowedHeaders: "*"
        allowCredentials: true


