spring:
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/MyProject
          jwk-set-uri: http://localhost:8080/realms/MyProject/protocol/openid-connect/certs
  application:
    name: Reclamation
  main:
    allow-bean-definition-overriding: true
