server:
  port: 8181

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/MyProject
          jwk-set-uri: http://localhost:8080/realms/MyProject/protocol/openid-connect/certs

#
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/MyProject
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

